import React from 'react'
import monk from './assets/images/monk.png'
import {BsCheckLg, BsCheck2} from 'react-icons/bs'
import tick from './assets/images/tick.png'
const About = () => {
  return (
    <>
    <div id='aboutUs' className="scroll-m-24 bg-green-50 min-h-fit border-solid border-2 ">
    <section className='text-center p-10 md:mx-32 mx-auto'>
    <div className='font-monteserrat text-4xl mb-4 font-semibold text-orange-400 '>About Us</div>
    <h1 className='font-roboto text-4xl mb-4 font-semibold text-black '>Yoga NFTs: Unleash Your Digital Serenity</h1>
    <p className='font-samarkan text-2xl mb-4 font-normal text-orange-6 '>Elevate your practice, own your inspiration.</p>


    <p className='font-monteserrat text-base  tracking-wider font-normal '>We thrive to create a digital place where health and mental wellness is the mantra of life. Therefore the name EK(Oneness) with Yoga(Unity) in the Verse(digital realm). Our mission is to build a strong community with like minded people from all across the world, who believe that with all the hardwork, there should also be a mental wellbeing. <br/><br/>

     Through our exclusively limited collection of 84 handcrafted Maha Guru’s yoga NFT collection, we invite the early adopters to this community. As we build EkYogaverse, a virtual space dedicated to the 84 Maha Guru and 8400 Gurus, we aim to provide a dynamic platform for exploration and engagement along with lifetime membership to help in creating better you</p>

     



    </section>

    <section className= 'md:mx-32 mx-auto flex md:flex-row gap-5 p-2 flex-col mb-8'>

   <img src={monk} alt='monk image '></img>
   {/* <div className=' border-solid border-4 border-cyan-950 font-roboto text-base font-normal tracking-wider px-4 '> */}
   <div className='font-roboto text-base font-normal tracking-wider px-4 '>


   {/* <p className=''><BsCheckLg className='inline-block h-[25px] w-[30px] text-orange-6'/> 

      <b> Exclusive Ownership: </b> As a Maha Guru NFT holder, you possess a digital masterpiece that is uniquely yours.
   </p> */}

   {points.map((point)=>{
    const {id,text} = point
    return (
    //     <p className='mb-2 '>
    //     <BsCheckLg className='inline-block h-[25px] w-[30px] text-orange-6'/>  
    //     <span className='border-solid border-4 border-cyan-950'>{text} </span>
    //  </p>
      <div className='mb-2' key={id}>
      <div className='flex items-start'>
        {/* <BsCheckLg  style={{height:'25px', width:'30px'}} className=' text-orange-6' /> */}
        <img src={tick} style={{height:'18px', width:'20px'}} className='mt-1'></img>
        
        <p
          className=' ml-2 '
        //   className='border-solid border-4 border-cyan-950 ml-2 p-2'
          dangerouslySetInnerHTML={{ __html: text }}
        />
      </div>
    </div>
    )

   })
   }

   </div>

    </section>
    </div>
    </>
  )
}

export default About

const points = [
    {id:1,
    text:" <b>Exclusive Ownership:</b>  As a Maha Guru NFT holder, you possess a digital masterpiece that is uniquely yours."},
    {id:2,
    text:" <b>Collectible Value:</b> Being an exclusive owner of this limited Maha Guru Yoga NFT, you become uniquely limited  and limited things always appreciate with time."},
    {id:3,
    text:"<b>Inspiring Artwork with Physical Copy:</b> When you buy the Maha Guru NFT you not only own a digital asset but also get a physical copy to represent the Maha Guru within you."},
    {id:4,
    text:" <b>Royalty:</b>  As the Maha Guru NFT owner, you receive a 1% royalty from the revenue generated by the NFT Art."},
    {id:5,
    text:"<b>Board Seat:</b> Gain the opportunity of actively participating in the governance and decision-making processes of the platform as a Board member of this EkYogaverse!"},
    {id:6,
    text:"<b>Lifetime Membership:</b> Join the Yoga NFT community for exclusive perks and connections. Enhance your yoga journey with Yogaverse, the online platform for yoga practitioners and art lovers."},




]